(define-foreign-enum-type (jack-options int)
  (jack-options->int int->jack-options)
  ((no-options jack-options/no-options) JackNullOption)
  ((no-start-server jack-options/no-start-server) JackNoStartServer)
  ((use-exact-name jack-options/use-exact-name) JackUseExactName)
  ((server-name jack-options/server-name) JackServerName)
  ((load-name jack-options/load-name) JackLoadName)
  ((load-init jack-options/load-init) JackLoadInit)
  ((session-id jack-options/session-id) JackSessionID))

(define-foreign-enum-type (jack-status int)
  (jack-status->int int->jack-status)
  ((failure status/failure) JackFailure)
  ((invalid-option status/invalid-option) JackInvalidOption)
  ((name-not-unique status/name-not-unique) JackNameNotUnique)
  ((server-started status/server-started) JackServerStarted)
  ((server-failed status/server-failed) JackServerFailed)
  ((server-error status/server-error) JackServerError)
  ((no-such-client status/no-such-client) JackNoSuchClient)
  ((load-failure status/load-failure) JackLoadFailure)
  ((init-failure status/init-failure) JackInitFailure)
  ((shm-failure status/shm-failure) JackShmFailure)
  ((version-error status/version-error) JackVersionError)
  ((backend-error status/backend-error) JackBackendError)
  ((client-zombie status/client-zombie) JackClientZombie))

(define-foreign-enum-type (jack-port-flags long)
  (jack-port-flags->long long->jack-port-flags)
  ((is-input flags/is-input) JackPortIsInput)
  ((is-output flags/is-output) JackPortIsOutput)
  ((is-physical flags/is-physical) JackPortIsPhysical)
  ((can-monitor flags/can-monitor) JackPortCanMonitor)
  ((is-terminal flags/is-terminal) JackPortIsTerminal))

